[files]
extend-exclude = [
    ".git/",
    "bignp256/tests/pkcs8.rs",
    "p224/src/arithmetic.rs",
    "p384/src/arithmetic.rs",
    "p384/tests/affine.rs",
]

[default]
extend-ignore-re = [
    # Patterns which appear to be 36 or more characters of Base64/Base64url
    '\b[0-9A-Za-z+/]{36,}\b',
    '\b[0-9A-Za-z_-]{36,}\b',
]

[default.extend-words]
# Authenticated Key Exchange
"AKE" = "AKE"
# Claus P. Schnorr
"Claus" = "Claus"
