[files]
extend-exclude = [
    ".git/",
    "bign256/tests/pkcs8.rs",
    "p224/src/arithmetic.rs",
    "p384/src/arithmetic.rs",
    "p384/tests/affine.rs",
]

[default.extend-words]
# Authenticated Key Exchange
"AKE" = "AKE"
# Claus P. Schnorr
"Claus" = "Claus"
